#!/usr/bin/env bash
# Author
author="Philip Mello <@Microsoft>"
# Version
version="1.0"
# License
license="MIT"
# Date
current_date=$(date +'%b %d, %Y')
# GitHub
github='https://github.com/PhilipMello/scripts/'
github2='https://github.com/AtomyCloud/scripts/'
# Microsoft Official Documentation
microsoft=''
echo "
# --------------------------------------------------------------
# Script     : Git Account Switch
# Description: 2 Github Accounts in one CLI
# Version    : $version
# Date       : $current_date
# Author     : $author
# License    : $license
# Github     : $github
# Github     : $github2
# Microsoft  : $microsoft
# --------------------------------------------------------------
# How to use: Execute ./git-switch
# Exemples:
# Manual: ./git-switch -h OR ./git-switch--h OR ./git-switch --help
# Change account using parameter: ./git-switch --account1
# --------------------------------------------------------------
"
WHITE=""
BLUE="\033[97;104m"
YELLOW="\033[97;103m"
CYAN="\033[97;106m"
MAGENTA="\033[97;45m"
GREEN="\033[97;102m"
RED="\033[97;41m"
ENDCOLOR="\e[0m"

function github_generate_sshkey() {
    # Generate SSH Key
    reap -p "Type your github email account": github_email_account
    ssh-keygen -t ed25519 -C "$github_email_account"
    echo "SSH key successfuly generated"
    cat ~/.ssh/id_ed25519.pub
    echo "Go to your GitHub Portal and add your SSH Key
    'https://github.com/settings/ssh/new'
    "
}

function github_connection_test() {
    # Github test connection
    echo "Github connection testing..."
    ssh -T git@github.com
}

function github_set_account() {
    # Github set account
    reap -p "Enter your Github Account Name": github_set_account_name
    reap -p "Enter your Github Account Email": github_set_account_email
    git config user.name "$github_set_account_name"
    git config user.email "$github_set_account_email"
}

function github_account_switch() {
    # Github Account Switch (2 Accounts)
    github_account1=$(cat ~/.ssh/id_ed25519_account1.pub | grep -E -o "\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,6}\b")
    github_account2=$(cat ~/.ssh/id_ed25519_account2.pub | grep -E -o "\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,6}\b")
    echo -e "You're logged in as:\n"
    ssh -T git@github.com
    echo "Choose an option:"
    echo "1. Switch to Account: $github_account1"
    echo "2. Switch to Account: $github_account2"
    read choice

    case $choice in
    1)
        cp ~/.ssh/id_ed25519_account1 ~/.ssh/id_ed25519
        cp ~/.ssh/id_ed25519_account1.pub ~/.ssh/id_ed25519.pub
        echo -e "Github Account #1 Selected!\n"
        ssh -T git@github.com
        ;;
    2)
        cp ~/.ssh/id_ed25519_account2 ~/.ssh/id_ed25519
        cp ~/.ssh/id_ed25519_account2.pub ~/.ssh/id_ed25519.pub
        echo -e "Github Account #2 Selected!\n"
        ssh -T git@github.com
        ;;
    *)
        echo "Invalid choice. Please select 1 or 2."
        ;;
esac
}

function github_fix_permissions() {
    # Git fix files permissions
    echo "Fixing SSH file permissions..."
    chown $USER:$USER -R  ~/.ssh
    chmod 700  ~/.ssh/
    chmod 600  ~/.ssh/id_ed25519_account1
    chmod 600  ~/.ssh/id_ed25519_account1.pub
    chmod 600  ~/.ssh/id_ed25519_account2
    chmod 600  ~/.ssh/id_ed25519_account2.pub
    echo "Files permissions has been fixed"
}

# <---

# Manual and Pipeline
manual() {
echo "Generate 2 SSH Keys and rename Github account to
id_ed25519_account1 and Github account 2 to id_ed25519_account2
in ~/.ssh
"
exit 0
}

if [[ $1 == "-h" || $1 == "--help" || $1 == "--h" ]]; then
    manual
    exit 1
elif [[ $1 == "--account1" ]]; then
    cp ~/.ssh/id_ed25519_account1 ~/.ssh/id_ed25519
    cp ~/.ssh/id_ed25519_account1.pub ~/.ssh/id_ed25519.pub
    echo -e "Github Account #1 has been selected!\n"
    ssh -T git@github.com
    exit 0
elif [[ $1 == "--account2" ]]; then
    cp ~/.ssh/id_ed25519_account2 ~/.ssh/id_ed25519
    cp ~/.ssh/id_ed25519_account2.pub ~/.ssh/id_ed25519.pub
    echo -e "Github Account #2 has been selected!\n"
    ssh -T git@github.com
    exit 0
fi

# --->

echo "Choose an option:"
echo "1. Switch GitHub Account"
echo "2. Generate SSH Key"
echo "3. Test Github SSH connection"
echo "4. Set Github account"
echo "5. Fix SSH file permissions"
read option

case $option in
    1)
        github_account_switch
        ;;
    2)  
        github_generate_sshkey
        ;;
    3)
        github_connection_test
        ;;
    4)
        github_set_account
        ;;
    5)
        github_fix_permissions
        ;;
    *)
        echo "Invalid option"
        ;;
esac